spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver 
    url: jdbc:mariadb://localhost:3306/MariaDB
    username: gimgabsin
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  
mybatis:
  type-aliases-package: com.example.demo.Mapper
  mapper-locations: sqlmapper/*.xml
  
 
